const QUESTIONS = [
  { id: 1, name: "The Lucky Painting", difficulty: "Easy", firm: "SIG", subject: "Expected Value", framework: "Law of Total Expectations", theme: "Options", formula_ids: ["F1","F67"] },
  { id: 2, name: "Roll Every Number", difficulty: "Easy", firm: "IMC", subject: "Expected Value", framework: "Recursive Expectations", theme: "Dice", formula_ids: ["F15","F16"] },
  { id: 3, name: "Number of Mondays", difficulty: "Medium", firm: "Optiver", subject: "Logic", framework: "Calendars", theme: null, formula_ids: [] },
  { id: 4, name: "Birthday Trio", difficulty: "Easy", firm: "SIG", subject: "Probability", framework: "Conditional Probability", theme: null, formula_ids: ["F6","F7"] },
  { id: 5, name: "Ages Around The Table", difficulty: "Medium", firm: "SIG", subject: "Probability", framework: "Combinatorics", theme: null, formula_ids: ["F9","F12"] },
  { id: 6, name: "Median of Three Dice", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Symmetry", theme: "Dice", formula_ids: ["F59"] },
  { id: 7, name: "Jack Pot", difficulty: "Medium", firm: "Two Sigma", subject: "Expected Value", framework: "Combinatorics", theme: "Games|Cards", formula_ids: ["F9"] },
  { id: 8, name: "Bounding Rsq", difficulty: "Medium", firm: "Millennium", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50","F52"] },
  { id: 9, name: "Proving OLS", difficulty: "Easy", firm: "MAN Numeric", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50"] },
  { id: 10, name: "Proving Variance of Sums", difficulty: "Easy", firm: "Arrowstreet", subject: "Statistics", framework: "Covariance", theme: null, formula_ids: ["F30","F31","F32"] },
  { id: 11, name: "Optimal Jar Selection", difficulty: "Medium", firm: "DRW", subject: "Expected Value", framework: "Bayes|Games", theme: "Coins", formula_ids: ["F3","F55","F56"] },
  { id: 12, name: "How Many Players", difficulty: "Easy", firm: "Belvedere", subject: "Statistics", framework: null, theme: null, formula_ids: ["F62","F63"] },
  { id: 13, name: "Fastest 3 Horses in 25", difficulty: "Medium", firm: "Optiver", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 14, name: "Flip 3 Cards", difficulty: "Hard", firm: "Optiver", subject: "Expected Value", framework: "Dynamic Programming", theme: "Cards|Games", formula_ids: ["F57"] },
  { id: 15, name: "Inverse Betting", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Games", theme: null, formula_ids: ["F56"] },
  { id: 16, name: "Two Heads in Five", difficulty: "Easy", firm: "Jane Street", subject: "Probability", framework: "Combinatorics|Symmetry", theme: "Coins", formula_ids: ["F9","F59"] },
  { id: 17, name: "Painted Die", difficulty: "Easy", firm: "Jane Street", subject: "Probability", framework: "Not Or And", theme: "Dice", formula_ids: ["F4","F5"] },
  { id: 18, name: "Back To School Integral", difficulty: "Easy", firm: "Citadel", subject: "Math", framework: "Calculus", theme: null, formula_ids: ["F64"] },
  { id: 19, name: "To Re-roll or Not", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Games", theme: "Dice", formula_ids: ["F56"] },
  { id: 20, name: "Dice Roll Sum", difficulty: "Medium", firm: "Jane Street", subject: "Probability", framework: null, theme: null, formula_ids: ["F5"] },
  { id: 21, name: "Making Fibonaccis", difficulty: "Easy", firm: "Virtu", subject: "Coding", framework: null, theme: null, formula_ids: [] },
  { id: 22, name: "Guess the Hand Value", difficulty: "Medium", firm: "Optiver", subject: "Expected Value", framework: "Law of Total Expectations", theme: "Cards", formula_ids: ["F1"] },
  { id: 23, name: "Heavier Ball in 8", difficulty: "Medium", firm: "SIG", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 24, name: "Square Root of Five", difficulty: "Easy", firm: "Citadel", subject: "Math", framework: "Roots", theme: null, formula_ids: ["F14"] },
  { id: 25, name: "Rsq and Correlation", difficulty: "Easy", firm: "Point72", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50","F52"] },
  { id: 26, name: "Flipping a Coefficient", difficulty: "Easy", firm: "PanAgora", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50"] },
  { id: 27, name: "Sunny Days", difficulty: "Easy", firm: "SIG", subject: "Probability", framework: "Not Or And", theme: null, formula_ids: ["F4","F5"] },
  { id: 28, name: "Average of Residual", difficulty: "Easy", firm: "Acadian", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50","F53"] },
  { id: 29, name: "Biased Ruin", difficulty: "Medium", firm: "Optiver", subject: "Probability", framework: "Gamblers Ruin", theme: "Coins", formula_ids: ["F44"] },
  { id: 30, name: "Third Jack", difficulty: "Medium", firm: "IMC", subject: "Expected Value", framework: "Combinatorics|Games", theme: "Cards", formula_ids: ["F9","F56"] },
  { id: 31, name: "Multi-Variate Regression Overfitting", difficulty: "Medium", firm: "Schonfeld", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50","F52","F54"] },
  { id: 32, name: "EV of Doubled Deck", difficulty: "Easy", firm: "Optiver", subject: "Expected Value", framework: "Law of Total Expectations", theme: "Cards", formula_ids: ["F1"] },
  { id: 33, name: "Win Any Two", difficulty: "Medium", firm: "Optiver", subject: "Probability", framework: "Not Or And", theme: null, formula_ids: ["F4","F5"] },
  { id: 34, name: "Unfair Even Heads", difficulty: "Medium", firm: "Jane Street", subject: "Probability", framework: null, theme: "Coins", formula_ids: ["F59"] },
  { id: 35, name: "Sum of Odds Till 60", difficulty: "Easy", firm: "Jane Street", subject: "Math", framework: "Consecutive Summation", theme: null, formula_ids: ["F49","F51"] },
  { id: 36, name: "EV of 4 Coin Flips", difficulty: "Easy", firm: "Jane Street", subject: "Expected Value", framework: null, theme: "Coins|Games", formula_ids: ["F1"] },
  { id: 37, name: "Eleven or Twelve", difficulty: "Easy", firm: "Optiver", subject: "Probability", framework: null, theme: "Dice", formula_ids: ["F5"] },
  { id: 38, name: "Numeric Sequence", difficulty: "Hard", firm: "Optiver", subject: "Sequence", framework: null, theme: null, formula_ids: [] },
  { id: 39, name: "Orthogonality and Covariance", difficulty: "Medium", firm: "AQR", subject: "Statistics", framework: "Covariance", theme: null, formula_ids: ["F30","F32","F36"] },
  { id: 40, name: "Maximum Winnings", difficulty: "Medium", firm: "Five Rings", subject: "Expected Value", framework: "Games", theme: "Dice", formula_ids: ["F56"] },
  { id: 41, name: "Weighing Five Melons", difficulty: "Easy", firm: "Jane Street", subject: "Math", framework: "Grade School Math", theme: null, formula_ids: [] },
  { id: 42, name: "Distinct Digit Date", difficulty: "Hard", firm: "Jane Street", subject: "Logic", framework: "Calendars", theme: null, formula_ids: [] },
  { id: 43, name: "Six Sixes", difficulty: "Hard", firm: "Jump Trading", subject: "Expected Value", framework: "Induction", theme: "Dice", formula_ids: ["F17"] },
  { id: 44, name: "Encoding Salaries", difficulty: "Medium", firm: "Optiver", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 45, name: "Flipping Home", difficulty: "Medium", firm: "Optiver", subject: "Probability", framework: "Not Or And", theme: "Coins", formula_ids: ["F4","F5"] },
  { id: 46, name: "Significant Phone Numbers", difficulty: "Easy", firm: "DE Shaw", subject: "Probability", framework: "Statistics", theme: null, formula_ids: ["F18"] },
  { id: 47, name: "Square Root of Forty-Six", difficulty: "Medium", firm: "Five Rings", subject: "Math", framework: "Roots", theme: null, formula_ids: ["F14"] },
  { id: 48, name: "Best Time to Buy and Sell Stock III", difficulty: "Hard", firm: "Radix", subject: "Coding", framework: null, theme: null, formula_ids: ["F51"] },
  { id: 49, name: "1d OLS Proof", difficulty: "Easy", firm: "Arrowstreet", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50","F51"] },
  { id: 50, name: "Six Card Expected Value", difficulty: "Hard", firm: "IMC", subject: "Expected Value", framework: "Dynamic Programming", theme: "Games|Cards", formula_ids: ["F57"] },
  { id: 51, name: "Regression with a Control", difficulty: "Easy", firm: "Point72", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50"] },
  { id: 52, name: "Lying about Age", difficulty: "Medium", firm: "SIG", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 53, name: "Biased Coin in Urn", difficulty: "Easy", firm: "Jane Street", subject: "Probability", framework: "Bayes", theme: "Coins", formula_ids: ["F3"] },
  { id: 54, name: "Lucky 7 Draw II", difficulty: "Medium", firm: "Five Rings", subject: "Expected Value", framework: "Combinatorics|Games", theme: "Cards", formula_ids: ["F9","F56"] },
  { id: 55, name: "Taking out the Constant", difficulty: "Medium", firm: "Millennium", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50","F51"] },
  { id: 56, name: "Half Increment Sequence", difficulty: "Hard", firm: "Optiver", subject: "Sequence", framework: null, theme: null, formula_ids: [] },
  { id: 57, name: "Heavier Ball in 12", difficulty: "Hard", firm: "IMC", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 58, name: "Linear Arbitrage", difficulty: "Easy", firm: "WorldQuant", subject: "Covariance", framework: "Games", theme: null, formula_ids: ["F30","F56","F66"] },
  { id: 59, name: "Fifteen Degree Right Triangle", difficulty: "Medium", firm: "Five Rings", subject: "Math", framework: "Grade School Math", theme: null, formula_ids: [] },
  { id: 60, name: "Top Duo Sprinter", difficulty: "Easy", firm: "Belvedere", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 61, name: "Capture the Center", difficulty: "Medium", firm: "Akuna", subject: "Probability", framework: "Law of Total Probability", theme: null, formula_ids: ["F2","F60"] },
  { id: 62, name: "Burning Ropes", difficulty: "Medium", firm: "Jane Street", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 63, name: "Chance of Rain", difficulty: "Medium", firm: "Jane Street", subject: "Probability", framework: "Conditional Probability", theme: null, formula_ids: ["F7"] },
  { id: 64, name: "Max Two Dice", difficulty: "Medium", firm: "Jump Trading", subject: "Expected Value", framework: null, theme: "Dice", formula_ids: ["F29"] },
  { id: 65, name: "Frog on a Square", difficulty: "Hard", firm: "SIG", subject: "Logic", framework: "Symmetry", theme: null, formula_ids: ["F9","F59"] },
  { id: 66, name: "Random Tic-Tac-Toe", difficulty: "Medium", firm: "SIG", subject: "Expected Value", framework: "Games", theme: null, formula_ids: ["F56"] },
  { id: 67, name: "Back to School Calculus", difficulty: "Medium", firm: "Citadel", subject: "Math", framework: "Calculus", theme: null, formula_ids: ["F64"] },
  { id: 68, name: "Valley Numbers", difficulty: "Medium", firm: "Belvedere", subject: "Combinatorics", framework: null, theme: null, formula_ids: ["F9"] },
  { id: 69, name: "Minimum of 100 Falling Cards", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Law of Total Expectations", theme: null, formula_ids: ["F1"] },
  { id: 70, name: "Conditional Normals", difficulty: "Easy", firm: "Akuna", subject: "Probability", framework: "Distributions", theme: null, formula_ids: ["F3","F20","F27"] },
  { id: 71, name: "Numeric Sequence (II)", difficulty: "Hard", firm: "Optiver", subject: "Sequence", framework: null, theme: null, formula_ids: [] },
  { id: 72, name: "Seven Shared Birthdays", difficulty: "Easy", firm: "Jane Street", subject: "Logic", framework: "Pigeon Hole", theme: null, formula_ids: ["F61"] },
  { id: 73, name: "100 Marbles", difficulty: "Easy", firm: "CTC", subject: "Expected Value", framework: "Games", theme: null, formula_ids: ["F55","F56"] },
  { id: 74, name: "Five Greedy Pirates", difficulty: "Medium", firm: "SIG", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 75, name: "Large Heads", difficulty: "Easy", firm: "SIG", subject: "Probability", framework: "Distributions", theme: null, formula_ids: ["F18","F20","F21"] },
  { id: 76, name: "Giant Sausage", difficulty: "Easy", firm: "Flow", subject: "Expected Value", framework: "Games", theme: null, formula_ids: ["F56"] },
  { id: 77, name: "Numeric Sequence (III)", difficulty: "Medium", firm: "Optiver", subject: "Sequence", framework: null, theme: null, formula_ids: [] },
  { id: 78, name: "Diamond Majority", difficulty: "Easy", firm: "Citadel", subject: "Probability", framework: "Combinatorics", theme: null, formula_ids: ["F9"] },
  { id: 79, name: "Lucky Seven Slots", difficulty: "Medium", firm: "Optiver", subject: "Expected Value", framework: "Games", theme: null, formula_ids: ["F56"] },
  { id: 80, name: "Three Fishermen", difficulty: "Medium", firm: "IMC", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 81, name: "Two vs Ten", difficulty: "Easy", firm: "SIG", subject: "Math", framework: "Roots", theme: null, formula_ids: ["F14"] },
  { id: 82, name: "Reverse Wagers", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Games", theme: null, formula_ids: ["F56"] },
  { id: 83, name: "Expected Days Until Bad Day", difficulty: "Medium", firm: "SIG", subject: "Expected Value", framework: "Recursive Expectations", theme: null, formula_ids: ["F16"] },
  { id: 84, name: "Variance of Points on a Plane", difficulty: "Medium", firm: "Citadel Securities", subject: "Expected Value", framework: "Variance", theme: null, formula_ids: ["F30","F52"] },
  { id: 85, name: "Boxcars", difficulty: "Easy", firm: "Jane Street", subject: "Probability", framework: "Bayes", theme: "Dice", formula_ids: ["F3"] },
  { id: 86, name: "Prove Correlation Matrix is PSD", difficulty: "Easy", firm: "Arrowstreet", subject: "Statistics", framework: "Linear Algebra|Covariance", theme: null, formula_ids: ["F30","F38","F39"] },
  { id: 87, name: "Square Roots", difficulty: "Medium", firm: "Optiver", subject: "Math", framework: "Roots", theme: null, formula_ids: ["F14"] },
  { id: 88, name: "Fifty Heads and Fifty Tails", difficulty: "Hard", firm: "Optiver", subject: "Probability", framework: "Combinatorics|Estimation", theme: "Coins", formula_ids: ["F9","F14"] },
  { id: 89, name: "Independence and Covariance", difficulty: "Medium", firm: "Akuna", subject: "Statistics", framework: "Covariance", theme: null, formula_ids: ["F30","F32"] },
  { id: 90, name: "Coke vs. Pepsi", difficulty: "Medium", firm: "SIG", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 91, name: "Multiply to 10000", difficulty: "Medium", firm: "Jane Street", subject: "Math", framework: "Constant Product", theme: null, formula_ids: ["F69"] },
  { id: 92, name: "Five-Hundred Fifty Heads", difficulty: "Medium", firm: "DE Shaw", subject: "Probability", framework: "Distributions", theme: "Coins", formula_ids: ["F20","F21"] },
  { id: 93, name: "Race to Bankruptcy", difficulty: "Medium", firm: "Optiver", subject: "Probability", framework: "Gamblers Ruin", theme: "Coins", formula_ids: ["F44"] },
  { id: 94, name: "Moon Boys", difficulty: "Easy", firm: "Belvedere", subject: "Expected Value", framework: null, theme: null, formula_ids: [] },
  { id: 95, name: "Sum of Four Prime Numbers", difficulty: "Easy", firm: "Jane Street", subject: "Probability", framework: "Combinatorics", theme: null, formula_ids: ["F9"] },
  { id: 96, name: "Russian Roulette - Half Full", difficulty: "Easy", firm: "Tower Research", subject: "Probability", framework: "Conditional Probability", theme: null, formula_ids: ["F7"] },
  { id: 97, name: "Annualizing Volatility", difficulty: "Easy", firm: "Point72", subject: "Statistics", framework: "Covariance", theme: null, formula_ids: ["F30","F32","F37"] },
  { id: 98, name: "Correlation 1", difficulty: "Easy", firm: "AQR", subject: "Statistics", framework: "Covariance", theme: null, formula_ids: ["F30","F32"] },
  { id: 99, name: "Betting Even-Odd", difficulty: "Easy", firm: "CTC", subject: "Expected Value", framework: "Games", theme: "Dice", formula_ids: ["F56"] },
  { id: 100, name: "Three Queens Five Cards", difficulty: "Easy", firm: "Five Rings", subject: "Combinatorics", framework: null, theme: "Cards", formula_ids: ["F9"] },
  { id: 101, name: "Unlucky Horse", difficulty: "Easy", firm: "SIG", subject: "Probability", framework: "Bayes", theme: null, formula_ids: ["F3"] },
  { id: 102, name: "Fair Bias", difficulty: "Easy", firm: "Akuna", subject: "Probability", framework: null, theme: null, formula_ids: ["F6"] },
  { id: 103, name: "Covariance of Sums", difficulty: "Easy", firm: "AQR", subject: "Statistics", framework: "Covariance", theme: null, formula_ids: ["F30","F32","F33"] },
  { id: 104, name: "Buff Traders", difficulty: "Easy", firm: "Belvedere", subject: "Math", framework: null, theme: null, formula_ids: [] },
  { id: 105, name: "Mice in a Room", difficulty: "Easy", firm: "Virtu", subject: "Probability", framework: "Combinatorics", theme: null, formula_ids: ["F9"] },
  { id: 106, name: "April 15th 2142", difficulty: "Hard", firm: "Jane Street", subject: "Logic", framework: "Calendars", theme: null, formula_ids: [] },
  { id: 107, name: "Variance of Die Roll", difficulty: "Easy", firm: "Optiver", subject: "Expected Value", framework: "Variance", theme: "Dice", formula_ids: ["F30"] },
  { id: 108, name: "Probability Child is a Boy", difficulty: "Easy", firm: "Optiver", subject: "Probability", framework: "Bayes", theme: null, formula_ids: ["F3"] },
  { id: 109, name: "Multiples of Twenty-Two", difficulty: "Easy", firm: "Optiver", subject: "Math", framework: "Multiples|Divisibility", theme: null, formula_ids: ["F69"] },
  { id: 110, name: "Bounding Correlation", difficulty: "Easy", firm: "Point72", subject: "Statistics", framework: "Covariance", theme: null, formula_ids: ["F30","F32"] },
  { id: 111, name: "Coupled Covariance", difficulty: "Medium", firm: "SIG", subject: "Statistics", framework: "Linear Algebra", theme: null, formula_ids: ["F38","F41","F42"] },
  { id: 112, name: "Exact Change", difficulty: "Easy", firm: "Optiver", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 113, name: "Counting Handshakes", difficulty: "Easy", firm: "Jane Street", subject: "Probability", framework: "Combinatorics", theme: null, formula_ids: ["F9"] },
  { id: 114, name: "Heads Again", difficulty: "Easy", firm: "Jane Street", subject: "Probability", framework: "Bayes", theme: "Coins", formula_ids: ["F3"] },
  { id: 115, name: "Spot the Unfair Coin", difficulty: "Easy", firm: "HRT", subject: "Probability", framework: "Bayes", theme: null, formula_ids: ["F3"] },
  { id: 116, name: "Points in a Semi-Circle", difficulty: "Medium", firm: "HRT", subject: "Probability", framework: "Not Or And", theme: null, formula_ids: ["F4","F5"] },
  { id: 117, name: "Formula for Rsq", difficulty: "Medium", firm: "Point72", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50","F52","F53"] },
  { id: 118, name: "Just Shy of a Dozen", difficulty: "Medium", firm: "SIG", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 119, name: "Orthogonality of Epsilon", difficulty: "Medium", firm: "Point72", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50"] },
  { id: 120, name: "Triple 7s", difficulty: "Medium", firm: "Citadel", subject: "Expected Value", framework: null, theme: "Cards", formula_ids: ["F59"] },
  { id: 121, name: "Sum to Odd", difficulty: "Medium", firm: "Optiver", subject: "Probability", framework: "Combinatorics|Symmetry", theme: "Dice", formula_ids: ["F9","F59"] },
  { id: 122, name: "Under the Gun", difficulty: "Easy", firm: "Akuna", subject: "Probability", framework: null, theme: null, formula_ids: [] },
  { id: 123, name: "Profitable Wheat", difficulty: "Easy", firm: "Belvedere", subject: "Statistics", framework: null, theme: null, formula_ids: [] },
  { id: 124, name: "Numeric Sequence (IV)", difficulty: "Medium", firm: "Optiver", subject: "Sequence", framework: null, theme: null, formula_ids: ["F68"] },
  { id: 125, name: "Bounding Variance", difficulty: "Easy", firm: "Robeco", subject: "Statistics", framework: "Covariance", theme: null, formula_ids: ["F30","F31","F32","F35"] },
  { id: 126, name: "Double-Headed", difficulty: "Easy", firm: "Belvedere", subject: "Probability", framework: "Bayes", theme: null, formula_ids: ["F3"] },
  { id: 127, name: "Folding Socks", difficulty: "Medium", firm: "Flow", subject: "Probability", framework: "Combinatorics", theme: null, formula_ids: ["F9"] },
  { id: 128, name: "Prime Number Program", difficulty: "Medium", firm: "Citadel", subject: "Coding", framework: null, theme: null, formula_ids: [] },
  { id: 129, name: "Sum of Evens Till 100", difficulty: "Easy", firm: "Jane Street", subject: "Math", framework: "Consecutive Summation", theme: null, formula_ids: ["F49"] },
  { id: 130, name: "First Lucky 7", difficulty: "Medium", firm: "Optiver", subject: "Expected Value", framework: null, theme: "Cards", formula_ids: ["F59"] },
  { id: 131, name: "When to Cash Out", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Games", theme: "Dice", formula_ids: ["F56"] },
  { id: 132, name: "Massive Digit Sum", difficulty: "Medium", firm: "Jane Street", subject: "Probability", framework: "Expected Value", theme: null, formula_ids: ["F68"] },
  { id: 133, name: "Odd Heads After N Flips", difficulty: "Medium", firm: "Jane Street", subject: "Probability", framework: "Symmetry", theme: "Coins", formula_ids: ["F9","F59"] },
  { id: 134, name: "Symmetric Numbers", difficulty: "Hard", firm: "Jane Street", subject: "Expected Value", framework: null, theme: null, formula_ids: ["F9","F22"] },
  { id: 135, name: "Domino Chessboard", difficulty: "Medium", firm: "IMC", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 136, name: "Cereal Box Expectations", difficulty: "Easy", firm: "Five Rings", subject: "Expected Value", framework: null, theme: null, formula_ids: ["F15","F16"] },
  { id: 137, name: "Regress on 2x Instead", difficulty: "Easy", firm: "AQR", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50","F51"] },
  { id: 138, name: "Larger Die Roll Wins", difficulty: "Easy", firm: "Jane Street", subject: "Expected Value", framework: "Law of Total Expectations", theme: "Dice|Games", formula_ids: ["F1"] },
  { id: 139, name: "Making Epsilon Uncorrelated", difficulty: "Medium", firm: "Millennium", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50","F53"] },
  { id: 140, name: "Matching Birthday", difficulty: "Easy", firm: "Jane Street", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 141, name: "Biased HH", difficulty: "Easy", firm: "SIG", subject: "Expected Value", framework: "Recursive Expectations", theme: "Coins", formula_ids: ["F16"] },
  { id: 142, name: "Bag of Balls", difficulty: "Easy", firm: "SIG", subject: "Probability", framework: "Conditional Probability", theme: null, formula_ids: ["F7"] },
  { id: 143, name: "Toss 10", difficulty: "Easy", firm: "Optiver", subject: "Probability", framework: "Symmetry", theme: "Cards", formula_ids: ["F59"] },
  { id: 144, name: "Eight Letter Word", difficulty: "Medium", firm: "Optiver", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 145, name: "Combining Two Uncorrelated Process", difficulty: "Medium", firm: "GSA", subject: "Statistics", framework: "Covariance", theme: null, formula_ids: ["F30","F32"] },
  { id: 146, name: "Alphabetic Sequence", difficulty: "Easy", firm: "Akuna", subject: "Sequence", framework: null, theme: null, formula_ids: [] },
  { id: 147, name: "Triple Min", difficulty: "Medium", firm: "SIG", subject: "Probability", framework: "Max/Min", theme: null, formula_ids: ["F28"] },
  { id: 148, name: "Prove Covariance Matrix is PSD", difficulty: "Easy", firm: "Millennium", subject: "Statistics", framework: "Linear Algebra|Covariance", theme: null, formula_ids: ["F30","F38","F39"] },
  { id: 149, name: "Coin Permutations", difficulty: "Hard", firm: "Citadel", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 150, name: "Normal Moments", difficulty: "Hard", firm: "Optiver", subject: "Probability", framework: "Distributions", theme: null, formula_ids: ["F14","F20","F24"] },
  { id: 151, name: "Consecutive Ones Binary String", difficulty: "Hard", firm: "SIG", subject: "Probability", framework: "Combinatorics", theme: null, formula_ids: ["F9"] },
  { id: 152, name: "Tennis Trivia", difficulty: "Easy", firm: "Belvedere", subject: "Expected Value", framework: "Recursive Expectations", theme: null, formula_ids: ["F16","F58"] },
  { id: 153, name: "Boarding a Train Drunk", difficulty: "Hard", firm: "Jane Street", subject: "Probability", framework: "Law of Total Probability|Induction|Symmetry", theme: null, formula_ids: ["F2","F17","F59","F71"] },
  { id: 154, name: "Prime Gambler", difficulty: "Easy", firm: "SIG", subject: "Expected Value", framework: "Games", theme: null, formula_ids: ["F56"] },
  { id: 155, name: "Three Coin Match", difficulty: "Easy", firm: "SIG", subject: "Expected Value", framework: "Games", theme: "Coins", formula_ids: ["F56"] },
  { id: 156, name: "Inconsistent Correlations", difficulty: "Medium", firm: "SIG", subject: "Statistics", framework: "Linear Algebra|Covariance", theme: null, formula_ids: ["F30","F38","F39","F40"] },
  { id: 157, name: "Biased Tails", difficulty: "Easy", firm: "SIG", subject: "Expected Value", framework: null, theme: "Dice", formula_ids: ["F69"] },
  { id: 158, name: "Color Collector", difficulty: "Medium", firm: "Citadel", subject: "Probability", framework: "Symmetry", theme: null, formula_ids: ["F59"] },
  { id: 159, name: "Multiply to 120", difficulty: "Medium", firm: "Jane Street", subject: "Math", framework: "Constant Product", theme: null, formula_ids: ["F69"] },
  { id: 160, name: "Numeric Sequence (V)", difficulty: "Medium", firm: "Optiver", subject: "Sequence", framework: null, theme: null, formula_ids: [] },
  { id: 161, name: "Equal Heads", difficulty: "Easy", firm: "SIG", subject: "Probability", framework: "Not Or And", theme: "Coins", formula_ids: ["F4","F5"] },
  { id: 162, name: "Four Player Guess Fair Coin Toss", difficulty: "Hard", firm: "Citadel", subject: "Probability", framework: "Combinatorics|Max/Min|Games", theme: "Coins", formula_ids: ["F9","F28","F56"] },
  { id: 163, name: "Triple Flip Game", difficulty: "Hard", firm: "Belvedere", subject: "Probability", framework: "Recursive Expectations", theme: null, formula_ids: ["F16"] },
  { id: 164, name: "Rolling Recent VWAP", difficulty: "Medium", firm: "Belvedere", subject: "Coding", framework: null, theme: null, formula_ids: [] },
  { id: 165, name: "Dice Bet with One Re-Roll", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Dynamic Programming", theme: "Dice|Games", formula_ids: ["F57"] },
  { id: 166, name: "Spaghetti Frenzy", difficulty: "Hard", firm: "HRT", subject: "Probability", framework: "Induction", theme: null, formula_ids: ["F17"] },
  { id: 167, name: "Efficient Power", difficulty: "Easy", firm: "Jane Street", subject: "Math", framework: null, theme: null, formula_ids: [] },
  { id: 168, name: "Coin Race", difficulty: "Easy", firm: "Optiver", subject: "Probability", framework: "Not Or And", theme: "Coins", formula_ids: ["F4","F5"] },
  { id: 169, name: "Matching Socks", difficulty: "Easy", firm: "Five Rings", subject: "Probability", framework: "Combinatorics", theme: null, formula_ids: ["F9"] },
  { id: 170, name: "A Row of Lightbulbs", difficulty: "Medium", firm: "SIG", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 171, name: "Meeting Chance", difficulty: "Medium", firm: "SIG", subject: "Probability", framework: null, theme: null, formula_ids: ["F22"] },
  { id: 172, name: "Even Number of Heads", difficulty: "Easy", firm: "Jane Street", subject: "Probability", framework: "Symmetry", theme: "Coins", formula_ids: ["F59"] },
  { id: 173, name: "Twenty-Four with Two Threes and Two Eights", difficulty: "Hard", firm: "Citadel", subject: "Math", framework: "Grade School Math", theme: null, formula_ids: [] },
  { id: 174, name: "Hot Hand", difficulty: "Hard", firm: "Belvedere", subject: "Probability", framework: "Induction", theme: null, formula_ids: ["F17"] },
  { id: 175, name: "Counting Fours", difficulty: "Medium", firm: "Citadel", subject: "Combinatorics", framework: null, theme: null, formula_ids: ["F4","F9"] },
  { id: 176, name: "Ratio of Inscribed Square", difficulty: "Easy", firm: "Five Rings", subject: "Math", framework: "Grade School Math", theme: null, formula_ids: [] },
  { id: 177, name: "Pair Heads", difficulty: "Easy", firm: "Citadel", subject: "Expected Value", framework: "Recursive Expectations", theme: null, formula_ids: ["F16"] },
  { id: 178, name: "Eight You Lose", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Games", theme: "Dice", formula_ids: ["F56"] },
  { id: 179, name: "Tennis Bet", difficulty: "Easy", firm: "DE Shaw", subject: "Probability", framework: "Calculus", theme: null, formula_ids: ["F64"] },
  { id: 180, name: "Fastest 3 Horses in 27", difficulty: "Medium", firm: "Optiver", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 181, name: "Best Time to Buy and Sell Stock", difficulty: "Easy", firm: "Radix", subject: "Coding", framework: null, theme: null, formula_ids: [] },
  { id: 182, name: "Flips Until HHH", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Recursive Expectations", theme: "Coins", formula_ids: ["F16"] },
  { id: 183, name: "Kings vs. Queens", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Games", theme: "Cards", formula_ids: ["F56"] },
  { id: 184, name: "Limit of x^x", difficulty: "Medium", firm: "Citadel Securities", subject: "Math", framework: "Exponents|Calculus", theme: null, formula_ids: ["F64","F65"] },
  { id: 185, name: "Random Savings", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Games", theme: null, formula_ids: ["F55","F56"] },
  { id: 186, name: "Draw Two Diamonds", difficulty: "Easy", firm: "Citadel", subject: "Probability", framework: "Combinatorics", theme: "Cards", formula_ids: ["F9"] },
  { id: 187, name: "Three Increasing Dice Roll", difficulty: "Medium", firm: "IMC", subject: "Probability", framework: "Combinatorics", theme: "Dice", formula_ids: ["F9"] },
  { id: 188, name: "Weird Factors Sequence", difficulty: "Hard", firm: "Akuna", subject: "Sequence", framework: null, theme: null, formula_ids: [] },
  { id: 189, name: "Two Consecutive Ones Less 100000", difficulty: "Medium", firm: "IMC", subject: "Combinatorics", framework: null, theme: null, formula_ids: ["F9"] },
  { id: 190, name: "Four Cards Expected Value", difficulty: "Hard", firm: "Optiver", subject: "Expected Value", framework: "Dynamic Programming|Games", theme: "Cards", formula_ids: ["F56","F57"] },
  { id: 191, name: "Apple Farmers Dilemma", difficulty: "Hard", firm: "Akuna", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 192, name: "Identical Non Empty Substrings", difficulty: "Easy", firm: "Virtu", subject: "Coding", framework: null, theme: null, formula_ids: [] },
  { id: 193, name: "Take it Or Leave It", difficulty: "Hard", firm: "Goldman Sachs", subject: "Expected Value", framework: "Recursive Expectations|Games", theme: null, formula_ids: ["F16","F55","F56"] },
  { id: 194, name: "Lucky 7 Draw", difficulty: "Medium", firm: "Five Rings", subject: "Expected Value", framework: "Combinatorics|Games", theme: "Cards", formula_ids: ["F9","F56"] },
  { id: 195, name: "Linearity of Covariance", difficulty: "Easy", firm: "Acadian", subject: "Statistics", framework: "Covariance", theme: null, formula_ids: ["F30","F32","F33"] },
  { id: 196, name: "Generous Bookie", difficulty: "Hard", firm: "SIG", subject: "Expected Value", framework: "Games", theme: null, formula_ids: ["F56"] },
  { id: 197, name: "Bias Variance Trade-Off", difficulty: "Medium", firm: "Schonfeld", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50","F54"] },
  { id: 198, name: "Best Time to Buy and Sell Stock II", difficulty: "Medium", firm: "Radix", subject: "Coding", framework: null, theme: null, formula_ids: [] },
  { id: 199, name: "Bowling Balls", difficulty: "Easy", firm: "Jane Street", subject: "Math", framework: "Grade School Math", theme: null, formula_ids: [] },
  { id: 200, name: "Timely-Untimely Truck", difficulty: "Easy", firm: "Optiver", subject: "Probability", framework: null, theme: null, formula_ids: ["F23"] },
  { id: 201, name: "Six Greedy Pirates", difficulty: "Hard", firm: "DE Shaw", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 202, name: "HexSpeak", difficulty: "Easy", firm: "Virtu", subject: "Coding", framework: null, theme: null, formula_ids: [] },
  { id: 203, name: "Up and To the Right", difficulty: "Medium", firm: "AQR", subject: "Statistics", framework: "Covariance", theme: null, formula_ids: ["F30","F32"] },
  { id: 204, name: "Win if You Roll the Same", difficulty: "Medium", firm: "SIG", subject: "Expected Value", framework: "Law of Total Expectations", theme: "Dice|Games", formula_ids: ["F1"] },
  { id: 205, name: "Utopian Dies", difficulty: "Hard", firm: "Belvedere", subject: "Probability", framework: null, theme: null, formula_ids: [] },
  { id: 206, name: "Common Pot Draw Game", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Games", theme: null, formula_ids: ["F56"] },
  { id: 207, name: "Round Table Discussion", difficulty: "Easy", firm: "SIG", subject: "Combinatorics", framework: null, theme: null, formula_ids: ["F12"] },
  { id: 208, name: "Dice Bet with Two Re-Rolls", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Dynamic Programming", theme: "Dice|Games", formula_ids: ["F57"] },
  { id: 209, name: "Chance of Winning at Deuce", difficulty: "Medium", firm: "Akuna", subject: "Probability", framework: "Law of Total Probability|Recursive Expectations", theme: null, formula_ids: ["F2","F16","F58"] },
  { id: 210, name: "Asset Impact Strategy Ranking", difficulty: "Easy", firm: "Belvedere", subject: "Coding", framework: null, theme: null, formula_ids: [] },
  { id: 211, name: "100 Story Egg Drop", difficulty: "Hard", firm: "WorldQuant", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 212, name: "Random Non-Singular NxN", difficulty: "Hard", firm: "Akuna", subject: "Probability", framework: "Linear Algebra", theme: null, formula_ids: ["F42"] },
  { id: 213, name: "RNG Game", difficulty: "Medium", firm: "Belvedere", subject: "Expected Value", framework: "Games", theme: null, formula_ids: ["F48","F56"] },
  { id: 214, name: "Comparing Normal Distributions", difficulty: "Easy", firm: "HRT", subject: "Probability", framework: "Distributions", theme: null, formula_ids: ["F20","F25"] },
  { id: 215, name: "Lions and Zebra", difficulty: "Medium", firm: "Citadel", subject: "Logic", framework: "Induction", theme: null, formula_ids: ["F17"] },
  { id: 216, name: "Infinite Sock Drawer", difficulty: "Easy", firm: "Jane Street", subject: "Expected Value", framework: "Law of Total Expectations", theme: null, formula_ids: ["F1"] },
  { id: 217, name: "Two Urns Monte", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Games", theme: null, formula_ids: ["F56"] },
  { id: 218, name: "Mixed Dice EV", difficulty: "Easy", firm: "SIG", subject: "Expected Value", framework: null, theme: "Dice", formula_ids: ["F1"] },
  { id: 219, name: "Table Robot", difficulty: "Medium", firm: "IMC", subject: "Expected Value", framework: "Recursive Expectations", theme: null, formula_ids: ["F16"] },
  { id: 220, name: "Local Height Maxima", difficulty: "Medium", firm: "Belvedere", subject: "Expected Value", framework: null, theme: null, formula_ids: ["F1","F59"] },
  { id: 221, name: "Constant Regression", difficulty: "Easy", firm: "Point72", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50"] },
  { id: 222, name: "Heavy Beam Balance", difficulty: "Medium", firm: "IMC", subject: "Probability", framework: "Combinatorics", theme: null, formula_ids: ["F9"] },
  { id: 223, name: "Odd Block", difficulty: "Medium", firm: "SIG", subject: "Probability", framework: "Combinatorics", theme: null, formula_ids: ["F9"] },
  { id: 224, name: "EV of a Card", difficulty: "Easy", firm: "Optiver", subject: "Expected Value", framework: null, theme: "Cards", formula_ids: ["F45"] },
  { id: 225, name: "Random Non-Singular 2x2", difficulty: "Hard", firm: "Akuna", subject: "Probability", framework: "Linear Algebra", theme: null, formula_ids: ["F42"] },
  { id: 226, name: "Six Greedy Pirates", difficulty: "Hard", firm: "DE Shaw", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 227, name: "HexSpeak", difficulty: "Easy", firm: "Virtu", subject: "Coding", framework: null, theme: null, formula_ids: [] },
  { id: 228, name: "Up and To the Right", difficulty: "Medium", firm: "AQR", subject: "Statistics", framework: "Covariance", theme: null, formula_ids: ["F30","F32"] },
  { id: 229, name: "Win if You Roll the Same", difficulty: "Medium", firm: "SIG", subject: "Expected Value", framework: "Law of Total Expectations", theme: "Dice|Games", formula_ids: ["F1"] },
  { id: 230, name: "Utopian Dies", difficulty: "Hard", firm: "Belvedere", subject: "Probability", framework: null, theme: null, formula_ids: [] },
  { id: 231, name: "Common Pot Draw Game", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Games", theme: null, formula_ids: ["F56"] },
  { id: 232, name: "Round Table Discussion", difficulty: "Easy", firm: "SIG", subject: "Combinatorics", framework: null, theme: null, formula_ids: ["F12"] },
  { id: 233, name: "Dice Bet with Two Re-Rolls", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Dynamic Programming", theme: "Dice|Games", formula_ids: ["F57"] },
  { id: 234, name: "Chance of Winning at Deuce", difficulty: "Medium", firm: "Akuna", subject: "Probability", framework: "Law of Total Probability|Recursive Expectations", theme: null, formula_ids: ["F2","F16","F58"] },
  { id: 235, name: "Asset Impact Strategy Ranking", difficulty: "Easy", firm: "Belvedere", subject: "Coding", framework: null, theme: null, formula_ids: [] },
  { id: 236, name: "100 Story Egg Drop", difficulty: "Hard", firm: "WorldQuant", subject: "Logic", framework: null, theme: null, formula_ids: [] },
  { id: 237, name: "Random Non-Singular NxN", difficulty: "Hard", firm: "Akuna", subject: "Probability", framework: "Linear Algebra", theme: null, formula_ids: ["F42"] },
  { id: 238, name: "RNG Game", difficulty: "Medium", firm: "Belvedere", subject: "Expected Value", framework: "Games", theme: null, formula_ids: ["F48","F56"] },
  { id: 239, name: "Comparing Normal Distributions", difficulty: "Easy", firm: "HRT", subject: "Probability", framework: "Distributions", theme: null, formula_ids: ["F20","F25"] },
  { id: 240, name: "Lions and Zebra", difficulty: "Medium", firm: "Citadel", subject: "Logic", framework: "Induction", theme: null, formula_ids: ["F17"] },
  { id: 241, name: "Infinite Sock Drawer", difficulty: "Easy", firm: "Jane Street", subject: "Expected Value", framework: "Law of Total Expectations", theme: null, formula_ids: ["F1"] },
  { id: 242, name: "Two Urns Monte", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Games", theme: null, formula_ids: ["F56"] },
  { id: 243, name: "Mixed Dice EV", difficulty: "Easy", firm: "SIG", subject: "Expected Value", framework: null, theme: "Dice", formula_ids: [] },
  { id: 244, name: "Table Robot", difficulty: "Medium", firm: "IMC", subject: "Expected Value", framework: "Recursive Expectations", theme: null, formula_ids: ["F16"] },
  { id: 245, name: "Local Height Maxima", difficulty: "Medium", firm: "Belvedere", subject: "Expected Value", framework: null, theme: null, formula_ids: [] },
  { id: 246, name: "Constant Regression", difficulty: "Easy", firm: "Point72", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50"] },
  { id: 247, name: "Heavy Beam Balance", difficulty: "Medium", firm: "IMC", subject: "Probability", framework: "Combinatorics", theme: null, formula_ids: ["F9"] },
  { id: 248, name: "Odd Block", difficulty: "Medium", firm: "SIG", subject: "Probability", framework: "Combinatorics", theme: null, formula_ids: ["F9"] },
  { id: 249, name: "EV of a Card", difficulty: "Easy", firm: "Optiver", subject: "Expected Value", framework: null, theme: "Cards", formula_ids: [] },
  { id: 250, name: "Random Non-Singular 2x2", difficulty: "Hard", firm: "Akuna", subject: "Probability", framework: "Linear Algebra", theme: null, formula_ids: ["F42"] },
  { id: 251, name: "Bounding Correlations of 3 RVs", difficulty: "Easy", firm: "Citadel", subject: "Statistics", framework: "Linear Algebra|Covariance", theme: null, formula_ids: ["F30","F38","F39","F40"] },
  { id: 252, name: "Hundred Die Bet", difficulty: "Medium", firm: "Jane Street", subject: "Expected Value", framework: "Recursive Expectations|Games", theme: "Dice", formula_ids: ["F16","F56"] },
  { id: 253, name: "Derive Normal MGF", difficulty: "Hard", firm: "Optiver", subject: "Probability", framework: "Distributions", theme: null, formula_ids: ["F20"] },
  { id: 254, name: "Rsq and N", difficulty: "Easy", firm: "AQR", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50","F52"] },
  { id: 255, name: "Firing Torpedoes", difficulty: "Easy", firm: "SIG", subject: "Probability", framework: "Not Or And", theme: null, formula_ids: ["F4","F5"] },
  { id: 256, name: "Efficient Exponentiation", difficulty: "Easy", firm: "Citadel", subject: "Coding", framework: null, theme: null, formula_ids: [] },
  { id: 257, name: "Loopy Noodles", difficulty: "Medium", firm: "HRT", subject: "Expected Value", framework: "Recursive Expectations", theme: null, formula_ids: ["F16"] },
  { id: 258, name: "Head Streak", difficulty: "Easy", firm: "Belvedere", subject: "Probability", framework: "Bayes", theme: null, formula_ids: ["F3"] },
  { id: 259, name: "Win in the Middle", difficulty: "Medium", firm: "IMC", subject: "Expected Value", framework: "Games", theme: "Dice", formula_ids: ["F55","F56"] },
  { id: 260, name: "Capture the Center II", difficulty: "Medium", firm: "Akuna", subject: "Probability", framework: "Law of Total Probability", theme: null, formula_ids: ["F2","F60"] },
  { id: 261, name: "Double a Dataset then Regress", difficulty: "Easy", firm: "Citadel", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50","F51"] },
  { id: 262, name: "OLS Features", difficulty: "Medium", firm: "Tower Research", subject: "Statistics", framework: "Econometrics", theme: null, formula_ids: ["F50"] },
  { id: 263, name: "Checker and Grid", difficulty: "Easy", firm: "IMC", subject: "Probability", framework: "Conditional Probability", theme: null, formula_ids: ["F7"] },
  { id: 264, name: "Two Games of Dice", difficulty: "Easy", firm: "Jane Street", subject: "Expected Value", framework: "Games", theme: "Dice", formula_ids: ["F56"] },
  { id: 265, name: "Normal Region", difficulty: "Easy", firm: "Jump Trading", subject: "Probability", framework: "Distributions|Symmetry", theme: null, formula_ids: ["F20","F59"] },
  { id: 266, name: "Dog in a Swamp", difficulty: "Medium", firm: "SIG", subject: "Math", framework: "Calculus", theme: null, formula_ids: ["F64"] },
  { id: 267, name: "Optimizing Hangman", difficulty: "Medium", firm: "Trexquant", subject: "Coding", framework: null, theme: null, formula_ids: [] },
  { id: 268, name: "Painted 3x3 Cube", difficulty: "Easy", firm: "HRT", subject: "Probability", framework: "Bayes", theme: null, formula_ids: ["F3"] },
  { id: 269, name: "Socks in Drawers", difficulty: "Easy", firm: "SIG", subject: "Probability", framework: "Law of Total Probability", theme: null, formula_ids: ["F2"] },
  { id: 270, name: "Twinkle Twinkle Little Star", difficulty: "Easy", firm: "Citadel", subject: "Probability", framework: "Not Or And", theme: null, formula_ids: ["F4","F5"] },
];

// Derived filter options
const FIRMS = [...new Set(QUESTIONS.map(q => q.firm))].sort();
const SUBJECTS = [...new Set(QUESTIONS.map(q => q.subject))].sort();
const DIFFICULTIES = ["Easy", "Medium", "Hard"];
const THEMES = [...new Set(QUESTIONS.filter(q => q.theme).flatMap(q => q.theme.split("|")))].sort();
